version: '2'
services:
  db:
    image: mdillon/postgis:9.5
    volumes:
      - ./.local_postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - 5000:5000
      # For local https testing.
      - 5001:5001
    environment:
      # PG* is used as defaults for psql
      - PGHOST=db
      - PGUSER=postgres
      - PGPASSWORD=postgres
      # default to use the dev enviroment.
      - APP_SETTINGS=settings.dev
      # Is this used?
      - ENVIRONMENT=dev
      - PYTHONIOENCODING=utf-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
    command: /app/docker/run_dev.sh
    # command: sleep infinity
