"""date_updated for all models.

Revision ID: 06f41c70d580
Revises: e10a83c1e5d5
Create Date: 2018-07-01 04:54:39.056124

"""

# revision identifiers, used by Alembic.
revision = '06f41c70d580'
down_revision = 'e10a83c1e5d5'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_url', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('match_result', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('profile', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('project', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rock1500_album', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rock1500_artist', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rock1500_pick', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rock1500_song', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('round', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('scope', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('team', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tournament', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trail', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trail_profile', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trail_progress', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('date_updated', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'date_updated')
    op.drop_column('trail_progress', 'date_updated')
    op.drop_column('trail_profile', 'date_updated')
    op.drop_column('trail', 'date_updated')
    op.drop_column('tournament', 'date_updated')
    op.drop_column('team', 'date_updated')
    op.drop_column('scope', 'date_updated')
    op.drop_column('round', 'date_updated')
    op.drop_column('rock1500_song', 'date_updated')
    op.drop_column('rock1500_pick', 'date_updated')
    op.drop_column('rock1500_artist', 'date_updated')
    op.drop_column('rock1500_album', 'date_updated')
    op.drop_column('project', 'date_updated')
    op.drop_column('profile', 'date_updated')
    op.drop_column('match_result', 'date_updated')
    op.drop_column('match', 'date_updated')
    op.drop_column('file_url', 'date_updated')
    op.drop_column('client', 'date_updated')
    # ### end Alembic commands ###
