"""Add album and ranks for songs

Revision ID: 159bf3954b8a
Revises: b8f88a242321
Create Date: 2017-08-30 21:59:02.630891

"""

# revision identifiers, used by Alembic.
revision = '159bf3954b8a'
down_revision = 'b8f88a242321'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rock1500_album',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('cover_art_url', sa.String(length=255), nullable=True),
    sa.Column('artist_id', shared.database.UUID(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['rock1500_artist.id'], name=op.f('fk_rock1500_album_artist_id_rock1500_artist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rock1500_album'))
    )
    op.create_index(op.f('ix_rock1500_album_name'), 'rock1500_album', ['name'], unique=True)
    op.add_column(u'rock1500_song', sa.Column('rank2015', sa.String(length=100), nullable=True))
    op.add_column(u'rock1500_song', sa.Column('rank2016', sa.String(length=100), nullable=True))
    op.add_column(u'rock1500_song', sa.Column('rank2017', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2017'), 'rock1500_song', ['rank2017'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2017'), table_name='rock1500_song')
    op.drop_column(u'rock1500_song', 'rank2017')
    op.drop_column(u'rock1500_song', 'rank2016')
    op.drop_column(u'rock1500_song', 'rank2015')
    op.drop_index(op.f('ix_rock1500_album_name'), table_name='rock1500_album')
    op.drop_table('rock1500_album')
    ### end Alembic commands ###
