"""Add rock.2020

Revision ID: 24100133b20b
Revises: 89c799dd6072
Create Date: 2020-10-24 23:51:03.871390

"""

# revision identifiers, used by Alembic.
revision = '24100133b20b'
down_revision = '89c799dd6072'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rank2020', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2020'), 'rock1500_song', ['rank2020'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2020'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rank2020')
    # ### end Alembic commands ###
