"""empty message

Revision ID: 30fe5e808670
Revises: 24100133b20b
Create Date: 2021-09-08 08:18:18.750445

"""

# revision identifiers, used by Alembic.
revision = '30fe5e808670'
down_revision = '24100133b20b'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rank2021', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2021'), 'rock1500_song', ['rank2021'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2021'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rank2021')
    # ### end Alembic commands ###
