"""unique rank2018

Revision ID: 350e932825b7
Revises: 368d1514fbe7
Create Date: 2019-08-28 01:36:41.389177

"""

# revision identifiers, used by Alembic.
revision = '350e932825b7'
down_revision = '368d1514fbe7'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rock1500_song_rank2018', table_name='rock1500_song')
    op.create_index(op.f('ix_rock1500_song_rank2018'), 'rock1500_song', ['rank2018'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2018'), table_name='rock1500_song')
    op.create_index('ix_rock1500_song_rank2018', 'rock1500_song', ['rank2018'], unique=False)
    # ### end Alembic commands ###
