"""Add rock1500 2019 fields

Revision ID: 37f9c951ce57
Revises: bf2270401a08
Create Date: 2019-08-26 21:32:54.836425

"""

# revision identifiers, used by Alembic.
revision = '37f9c951ce57'
down_revision = 'bf2270401a08'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_rock1500_pick_user_id_user'), 'rock1500_pick', 'user', ['user_id'], ['id'])
    op.add_column('rock1500_song', sa.Column('rank2018', sa.Integer(), nullable=True))
    op.add_column('rock1500_song', sa.Column('rank2019', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2018'), 'rock1500_song', ['rank2018'], unique=False)
    op.create_index(op.f('ix_rock1500_song_rank2019'), 'rock1500_song', ['rank2019'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2019'), table_name='rock1500_song')
    op.drop_index(op.f('ix_rock1500_song_rank2018'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rank2019')
    op.drop_column('rock1500_song', 'rank2018')
    op.drop_constraint(op.f('fk_rock1500_pick_user_id_user'), 'rock1500_pick', type_='foreignkey')
    # ### end Alembic commands ###
