"""unique rank2014

Revision ID: 3b736ba21b81
Revises: f32d736af695
Create Date: 2019-08-29 17:08:31.842556

"""

# revision identifiers, used by Alembic.
revision = '3b736ba21b81'
down_revision = 'f32d736af695'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rank2014', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2014'), 'rock1500_song', ['rank2014'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2014'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rank2014')
    # ### end Alembic commands ###
