"""Set activity on each profile.

Revision ID: 41e57a09bc93
Revises: a3ecb084f099
Create Date: 2018-03-31 02:28:58.275590

"""

# revision identifiers, used by Alembic.
revision = '41e57a09bc93'
down_revision = 'a3ecb084f099'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils
from trail.models import TrailProfile


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trail', 'activity')
    op.add_column('trail_profile', sa.Column('activity', sqlalchemy_utils.types.choice.ChoiceType(TrailProfile.ACTIVITIES), server_default='walk', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trail_profile', 'activity')
    op.add_column('trail', sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
