"""Add 2023 to rock song

Revision ID: 4f089c69eab8
Revises: 5f5cba7be7c0
Create Date: 2023-08-21 19:16:30.302950

"""

# revision identifiers, used by Alembic.
revision = '4f089c69eab8'
down_revision = '5f5cba7be7c0'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rank2023', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rank2023'), 'rock1500_song', ['rank2023'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2023'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rank2023')
    # ### end Alembic commands ###
