"""Add Tournament

Revision ID: 5641dc40f28c
Revises: 35245dae40c8
Create Date: 2017-01-17 20:53:06.118428

"""

# revision identifiers, used by Alembic.
revision = '5641dc40f28c'
down_revision = '35245dae40c8'

from alembic import op
import app
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', app.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round',
    sa.Column('id', app.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tournament_id', app.database.UUID(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', app.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tournament_id', app.database.UUID(length=32), nullable=True),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournament.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', app.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('round_id', app.database.UUID(length=32), nullable=True),
    sa.Column('homeTeam_id', app.database.UUID(length=32), nullable=True),
    sa.Column('awayTeam_id', app.database.UUID(length=32), nullable=True),
    sa.Column('played', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['awayTeam_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['homeTeam_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_table('team')
    op.drop_table('round')
    op.drop_table('tournament')
    ### end Alembic commands ###
