"""Add trail url.

Revision ID: 605c011dac99
Revises: 367ba9509429
Create Date: 2018-03-01 20:12:10.308890

"""

# revision identifiers, used by Alembic.
revision = '605c011dac99'
down_revision = '367ba9509429'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trail', sa.Column('trail_url', sa.String(), nullable=True))
    op.alter_column('user', 'profile_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_column('trail', 'trail_url')
    # ### end Alembic commands ###
