"""refactor trail models.

Revision ID: 6cf7ce34f0cc
Revises: 9819b6267107
Create Date: 2017-07-25 18:41:48.955154

"""

# revision identifiers, used by Alembic.
revision = '6cf7ce34f0cc'
down_revision = '9819b6267107'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql
from apps.trail.models import TrailProfile

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('activity', sqlalchemy_utils.types.choice.ChoiceType(TrailProfile.ACTIVITIES), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trail'))
    )
    op.create_table('trail_profile',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('user_id', shared.database.UUID(length=64), nullable=False),
    sa.Column('trail_id', shared.database.UUID(length=64), nullable=False),
    sa.Column('color', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trail_id'], ['trail.id'], name=op.f('fk_trail_profile_trail_id_trail'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_trail_profile_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trail_profile')),
    sa.UniqueConstraint('trail_id', 'user_id', name=op.f('uq_trail_profile_trail_id'))
    )
    op.create_table('trail_progress',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('trail_profile_id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['trail_profile_id'], ['trail_profile.id'], name=op.f('fk_trail_progress_trail_profile_id_trail_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trail_progress'))
    )
    op.drop_table('trail_ride')
    op.drop_table('trail_biker')
    op.drop_table('trail_walk')
    op.drop_table('trail_walker')
    op.drop_column(u'match', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'match', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_table('trail_walker',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'trail_walker_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('trail_walk',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('walker_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['walker_id'], [u'trail_walker.id'], name=u'trail_walk_walker_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'trail_walk_pkey')
    )
    op.create_table('trail_biker',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('color', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'trail_biker_pkey')
    )
    op.create_table('trail_ride',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('biker_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('distance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['biker_id'], [u'trail_biker.id'], name=u'trail_ride_biker_id_fkey', ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id', name=u'trail_ride_pkey')
    )
    op.drop_table('trail_progress')
    op.drop_table('trail_profile')
    op.drop_table('trail')
    ### end Alembic commands ###
