"""unique rank2015

Revision ID: 89c799dd6072
Revises: 3b736ba21b81
Create Date: 2019-08-29 19:00:44.916905

"""

# revision identifiers, used by Alembic.
revision = '89c799dd6072'
down_revision = '3b736ba21b81'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_rock1500_song_rank2015'), 'rock1500_song', ['rank2015'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rank2015'), table_name='rock1500_song')
    # ### end Alembic commands ###
