"""Make email unique.

Revision ID: 8a906e94392f
Revises: 06f41c70d580
Create Date: 2018-08-02 07:17:31.324380

"""

# revision identifiers, used by Alembic.
revision = '8a906e94392f'
down_revision = '06f41c70d580'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    # ### end Alembic commands ###
