"""initial

Revision ID: 8d094adcf437
Revises: 
Create Date: 2016-09-09 11:24:08.071236

"""

# revision identifiers, used by Alembic.
revision = '8d094adcf437'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_db2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rock1500_song')
    op.drop_table('rock1500')
    ### end Alembic commands ###

