"""Require a user for a pick.

Revision ID: 968bb88482cf
Revises: 159bf3954b8a
Create Date: 2017-09-07 22:40:32.724438

"""

# revision identifiers, used by Alembic.
revision = '968bb88482cf'
down_revision = '159bf3954b8a'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'rock1500_pick', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'rock1500_pick', 'user_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    ### end Alembic commands ###
