"""add trail models.

Revision ID: 9819b6267107
Revises: 30fa7a3010f2
Create Date: 2017-02-12 17:25:16.376928

"""

# revision identifiers, used by Alembic.
revision = '9819b6267107'
down_revision = '30fa7a3010f2'

from alembic import op
import app
import sqlalchemy as sa
import shared


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trail_biker',
    sa.Column('id', shared.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_walker',
    sa.Column('id', shared.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_ride',
    sa.Column('id', shared.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('biker_id', shared.database.UUID(length=32), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['biker_id'], ['trail_biker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trail_walk',
    sa.Column('id', shared.database.UUID(length=32), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('walker_id', shared.database.UUID(length=32), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['walker_id'], ['trail_walker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trail_walk')
    op.drop_table('trail_ride')
    op.drop_table('trail_walker')
    op.drop_table('trail_biker')
    ### end Alembic commands ###
