"""Unique scope, cascade delete.

Revision ID: 998f710572bf
Revises: 8a906e94392f
Create Date: 2018-08-04 02:12:19.402268

"""

# revision identifiers, used by Alembic.
revision = '998f710572bf'
down_revision = '8a906e94392f'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_api_client_scope_client_id_client', 'api_client_scope', type_='foreignkey')
    op.drop_constraint('fk_api_client_scope_scope_id_scope', 'api_client_scope', type_='foreignkey')
    op.create_foreign_key(op.f('fk_api_client_scope_client_id_client'), 'api_client_scope', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_api_client_scope_scope_id_scope'), 'api_client_scope', 'scope', ['scope_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_scope_name'), 'scope', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_scope_name'), 'scope', type_='unique')
    op.drop_constraint(op.f('fk_api_client_scope_scope_id_scope'), 'api_client_scope', type_='foreignkey')
    op.drop_constraint(op.f('fk_api_client_scope_client_id_client'), 'api_client_scope', type_='foreignkey')
    op.create_foreign_key('fk_api_client_scope_scope_id_scope', 'api_client_scope', 'scope', ['scope_id'], ['id'])
    op.create_foreign_key('fk_api_client_scope_client_id_client', 'api_client_scope', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
