"""Remove string ranks.

Revision ID: a37d61c36d5f
Revises: d431d763dbef
Create Date: 2018-09-21 02:05:07.604242

"""

# revision identifiers, used by Alembic.
revision = 'a37d61c36d5f'
down_revision = 'd431d763dbef'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rock1500_song', 'rank2016')
    op.drop_column('rock1500_song', 'rank2015')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rank2015', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('rock1500_song', sa.Column('rank2016', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
