"""initial rock models.

Revision ID: b8f88a242321
Revises: 6cf7ce34f0cc
Create Date: 2017-08-30 20:46:44.542092

"""

# revision identifiers, used by Alembic.
revision = 'b8f88a242321'
down_revision = '6cf7ce34f0cc'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rock1500_artist',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rock1500_artist'))
    )
    op.create_index(op.f('ix_rock1500_artist_name'), 'rock1500_artist', ['name'], unique=True)
    op.create_table('rock1500_song',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('artist_id', shared.database.UUID(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['rock1500_artist.id'], name=op.f('fk_rock1500_song_artist_id_rock1500_artist')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rock1500_song'))
    )
    op.create_index(op.f('ix_rock1500_song_title'), 'rock1500_song', ['title'], unique=True)
    op.create_table('rock1500_pick',
    sa.Column('id', shared.database.UUID(length=64), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('song_id', shared.database.UUID(length=64), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('user_id', shared.database.UUID(length=64), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['rock1500_song.id'], name=op.f('fk_rock1500_pick_song_id_rock1500_song')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rock1500_pick_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rock1500_pick'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rock1500_pick')
    op.drop_index(op.f('ix_rock1500_song_title'), table_name='rock1500_song')
    op.drop_table('rock1500_song')
    op.drop_index(op.f('ix_rock1500_artist_name'), table_name='rock1500_artist')
    op.drop_table('rock1500_artist')
    ### end Alembic commands ###
