"""Initial postgres

Revision ID: bdf15677c048
Revises: 
Create Date: 2016-09-09 11:05:49.833914

"""

# revision identifiers, used by Alembic.
revision = 'bdf15677c048'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()


def upgrade_():
    ### commands auto generated by Alembic - please adjust! ###

    ### end Alembic commands ###


def downgrade_():
    ### commands auto generated by Alembic - please adjust! ###

    ### end Alembic commands ###


def upgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade_db1():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def upgrade_db2():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rock1500',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rock_token', sa.String(), nullable=True),
    sa.Column('picks', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rock1500_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('band', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade_db2():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rock1500_song')
    op.drop_table('rock1500')
    ### end Alembic commands ###

