"""Add tournament creator

Revision ID: bf2270401a08
Revises: eacca06878f8
Create Date: 2018-10-14 04:16:49.194620

"""

# revision identifiers, used by Alembic.
revision = 'bf2270401a08'
down_revision = 'eacca06878f8'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament', sa.Column('creator_id', shared.database.UUID(length=64), nullable=False))
    op.create_foreign_key(op.f('fk_tournament_creator_id_user'), 'tournament', 'user', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_tournament_creator_id_user'), 'tournament', type_='foreignkey')
    op.drop_column('tournament', 'creator_id')
    # ### end Alembic commands ###
