"""Add rankThisYear

Revision ID: d431d763dbef
Revises: eac666649cf3
Create Date: 2018-09-08 22:59:08.741455

"""

# revision identifiers, used by Alembic.
revision = 'd431d763dbef'
down_revision = 'eac666649cf3'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rock1500_song', sa.Column('rankThisYear', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rock1500_song_rankThisYear'), 'rock1500_song', ['rankThisYear'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rock1500_song_rankThisYear'), table_name='rock1500_song')
    op.drop_column('rock1500_song', 'rankThisYear')
    # ### end Alembic commands ###
