"""Add admin to user.

Revision ID: eac666649cf3
Revises: 998f710572bf
Create Date: 2018-09-08 22:51:54.404672

"""

# revision identifiers, used by Alembic.
revision = 'eac666649cf3'
down_revision = '998f710572bf'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
