"""remove played from match

Revision ID: f617d20b8079
Revises: 278f28506a04
Create Date: 2017-09-17 13:18:09.582528

"""

# revision identifiers, used by Alembic.
revision = 'f617d20b8079'
down_revision = '278f28506a04'

from alembic import op
import app
import sqlalchemy as sa
import shared
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'match', 'played')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'match', sa.Column('played', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
