server {
    listen 80;
    server_name mudge.co.nz www.mudge.co.nz;
    # Redirect http to https.
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name mudge.co.nz www.mudge.co.nz;

    ssl_certificate /etc/letsencrypt/live/mudge.co.nz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mudge.co.nz/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    add_header Strict-Transport-Security max-age=15768000;

    location /.well-known {
        root /home/mudge/projects/pyauto/static/;
        allow all;
    }
    location /static {
        root /home/mudge/projects/pyauto/;
    }
    location /public {
        root /home/mudge/projects/Website/;
    }
    location / {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:8081;
    }
}
