server {
    listen 80;
    server_name stage.mudge.co.nz;

    location /.well-known {
        root /home/mudge/projects/stage-mudge/static/;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;

    server_name stage.mudge.co.nz;
    ssl_certificate /etc/letsencrypt/live/stage.mudge.co.nz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/stage.mudge.co.nz/privkey.pem;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    add_header Strict-Transport-Security max-age=15768000;

    location /.well-known {
        root /home/mudge/projects/stage-mudge/static/;
        allow all;
    }
    location /static {
        # Shared with prod - not meaningfully different per-environment,
        # and kept fresh by the same git pull deploy.sh/deploy-staging.sh
        # both run against.
        root /home/mudge/projects/pyauto/;
    }
    location / {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:8082;
    }
}
